apiVersion: v2
name: react-app
description: Helm chart for the Hello World React application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - react
  - frontend
  - nginx
maintainers:
  - name: techwalkwel98
